#ifndef LIBHISTO_VERSION_H
#define LIBHISTO_VERSION_H

#define HISTO_VERSION_MAJOR 0
#define HISTO_VERSION_MINOR 1
#define HISTO_VERSION_PATCH 0
#define HISTO_VERSION_STRING "0.1.0"

#endif /* LIBHISTO_VERSION_H */
